version: '3.8'

services:
  # Backend API (conectando ao PostgreSQL local do host)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gerenciador_backend_local
    env_file:
      - .env.docker
    environment:
      NODE_ENV: production
      PORT: 3001
      JWT_SECRET: ${JWT_SECRET:-minha_chave_jwt_super_secreta_local_123456789}
      FRONTEND_URL: http://localhost:3000
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY:-}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY:-}
      VAPID_EMAIL: ${VAPID_EMAIL:-admin@localhost.com}
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "3001:3001"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gerenciador_network

  # Frontend Next.js
  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.frontend
    container_name: gerenciador_frontend_local
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - gerenciador_network

volumes:
  uploads_data:

networks:
  gerenciador_network:
    driver: bridge